### ISSUE TITLE
请问你做了什么优化 ？

### ISSUE THREAD

**Issue by yunhe-lin** [GavinHome/flying-redux#2]

**Comment by GavinHome** [comment]
1.支持flutter3.x
2.删掉了旧版的一堆无用的adapter，只保留了flowadapter
3.精简了flowadapter逻辑

整体上代码结构没有变化，就是删除了很多无用的代码

**Comment by yunhe-lin** [comment]
为何不在fish上提pr ？

**Comment by GavinHome** [comment]
fish上根本就没人合并，你看里面有五个，都很久了，没人维护了，好多人估计都是自己改代码，我这也是公司项目没办法，还是想用fish的这套风格，就自己改了一下，大体上保留了fish的大部分代码，局部觉得没有必要的就删除了
