### ISSUE TITLE
请问这个是持续更新呢,还是看心情看情况的

### ISSUE THREAD

**Issue by foolishlittlefox** [GavinHome/flying-redux#3]
fish_redux已经是个坑了,所以想确认下

**Comment by GavinHome** [comment]
> fish_redux已经是个坑了,所以想确认下

在fish这件事上，我也被坑了，所以我就自己改，我会一直更新必须的修改项，不会像getx那样无节制的加功能，并且只做状态管理这一件事情，因为目前我只是一个人在做
