### ISSUE TITLE
是否支持接口层下发组件名，客户端进行页面组装

### ISSUE THREAD

**Issue by chenyinghong** [GavinHome/flying-redux#4]
请教个问题，这里的Page 使用Commponent 组装的时候，还是要在代码层写死对吧，是否可以支持，接口层下发组件名，然后又框架来进行组装呢？

**Comment by GavinHome** [comment]
> 请教个问题，这里的Page 使用Commponent 组装的时候，还是要在代码层写死对吧，是否可以支持，接口层下发组件名，然后又框架来进行组装呢？

你好，意思是在Page中渲染哪些组件是由接口返回的确定？如果是我理解的这样的话，理论上是可行的，可以参考Todos示例，比如插槽中的report组件，类似这样注册进来，接口返回哪些就渲染哪些，通过组件名称，例如“report”来渲染，但布局相关的逻辑需要事先在page中动态处理好

**Comment by chenyinghong** [comment]
> > 请教个问题，这里的Page 使用Commponent 组装的时候，还是要在代码层写死对吧，是否可以支持，接口层下发组件名，然后又框架来进行组装呢？
> 
> 你好，意思是在Page中渲染哪些组件是由接口返回的确定？如果是我理解的这样的话，理论上是可行的，可以参考Todos示例，比如插槽中的report组件，类似这样注册进来，接口返回哪些就渲染哪些，通过组件名称，例如“report”来渲染，但布局相关的逻辑需要事先在page中动态处理好

是的，本身我认为组装式框架的Page构成就应该是大量的Component，然后由后端运营系统来配置式组装页面的组件顺序，这里的Todos 可以再多写一些demo吗？   感觉跟fish_redux 差异体现不明显，比如哪些地方做出了调整，考量是啥。

**Comment by GavinHome** [comment]
> > > 请教个问题，这里的Page 使用Commponent 组装的时候，还是要在代码层写死对吧，是否可以支持，接口层下发组件名，然后又框架来进行组装呢？
> > 
> > 
> > 你好，意思是在Page中渲染哪些组件是由接口返回的确定？如果是我理解的这样的话，理论上是可行的，可以参考Todos示例，比如插槽中的report组件，类似这样注册进来，接口返回哪些就渲染哪些，通过组件名称，例如“report”来渲染，但布局相关的逻辑需要事先在page中动态处理好
> 
> 是的，本身我认为组装式框架的Page构成就应该是大量的Component，然后由后端运营系统来配置式组装页面的组件顺序，这里的Todos 可以再多写一些demo吗？ 感觉跟fish_redux 差异体现不明显，比如哪些地方做出了调整，考量是啥。

1. 其实在使用上和fish的区别不大，若在公司项目上有顾虑，可以考虑基于fish来改造；这个package就是基于fish改造的，fish的pr没有人合并，不支持最新的flutter版本等等都是考虑的因素，本质上设计理念和fish是相同的，只是删除了很多冗余的不必须的类，比如增强监听的中间件（全局），adapter重构（去除冗余过时的类）等；除此之外，生命周期，渲染逻辑，代码组织理念等都是没有变化的，仅仅重构。
2. Todos本身已经足以说明常用的情况，可能你们需要的是基于业务的demo，应在具体项目中试验，但我个人觉得手机端大量的动态的组件，如果业务复杂，可能要考虑渲染问题，比如性能，毕竟手机端处理大量的渲染本身就有局限性。这部分也可实际测试后评估。
3. 无论用什么方式或这用哪个package，都能实现你说的需求。
