### ISSUE TITLE
从Fish Redux迁移到Flying Redux

### ISSUE THREAD

**Issue by arshcaria** [GavinHome/flying-redux#5]
请问从Fish Redux迁移到Flying Redux的话，是否有相关指南？

**Comment by GavinHome** [comment]
这个基于flutter3.x,所以首先考虑的是flutter的升级成本，fish redux到flying redux 除了adapter外，没有太大区别， 改个包名字就能用， 只保留了flow adapter， 所以对旧代码唯一修改的就是涉及adapter这块，其他例如代码结构等都没有任何区别
